baseURL = 'https://luke.marzen.me/'
# baseURL = 'https://lmarzen.github.io/blog/'
languageCode = 'en-us'
title = 'Under Construction'
theme = 'hugo-bearblog'
copyright = 'Copyright (C) 2023  Luke Marzen'
[params]
  hideMadeWithLine = true
