baseURL = 'https://luke.marzen.me/'
# baseURL = 'https://lmarzen.github.io/blog/'
languageCode = 'en-us'
title = 'Under Construction'
theme = 'hugo-bearblog'
copyright = 'Copyright © 2023-{year} Luke Marzen. All rights reserved.'
[params]
  hideCopyrightNotice = false
  hideMadeWithLine = true
