baseURL = 'https://luke.marzen.me/'
# baseURL = 'https://lmarzen.github.io/'

languageCode = 'en-us'
theme = 'hugo-bearblog'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

title = 'Luke Marzen'
author = "Luke Marzen"
copyright = 'Copyright © 2023 Luke Marzen. All rights reserved.'
# copyright = 'Copyright © 2023-2024 Luke Marzen. All rights reserved.'


# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
#disableKinds = ["taxonomy"]
#ignoreErrors = ["error-disable-taxonomy"]
#[permalinks]
#  blog = "/:slug/"
#  tags = "/blog/:slug"

[params]
  hideCopyrightNotice = false
  hideMadeWithLine = true

  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  description = '''Luke Marzen's personal blog.'''
  # images = ['images/share.png']
  title = 'Luke Marzen'

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "favicon.svg"

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "Jan 02, 2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # enable html in markdown files.
      unsafe = true
