[build]
  publish = "public"
  command = "make build"

  [build.environment]
    HUGO_VERSION = "0.122.0"

[context.production.environment]
  HUGO_ENV           = "production"
  # HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "make build"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "make preview"

[context.branch-deploy]
  command = "make publish"

[context.next.environment]
  # HUGO_ENABLEGITINFO = "true"

# [[redirects]]
#   from   = "/npmjs/*"
#   to     = "/npmjs/"
#   status = 200
